=== cyrsis/LearnCSharp/_Basic/xml-syntax-fundamentals/8-xml-syntax-fundamentals-m08-validity-exercise-files/invoice.dtd
<!ENTITY % contact "( name, address )">
<!ELEMENT invoice ( buyer, seller, detail, totals )>
<!ELEMENT buyer ( %contact; )>
<!ELEMENT seller ( %contact; )>
<!ELEMENT detail ( line+ )>
<!ELEMENT line ( description, quantity, each, total )>
<!ELEMENT totals ( preTax, tax*, total )>
<!ELEMENT name ( #PCDATA )>
<!ELEMENT address ( #PCDATA )>
<!ELEMENT description ( #PCDATA )>
<!ELEMENT quantity ( #PCDATA )>
<!ELEMENT each ( #PCDATA )>
<!ELEMENT preTax ( #PCDATA )>
<!ELEMENT tax ( #PCDATA )>
<!ELEMENT total ( #PCDATA )>
<!ATTLIST total currency ( GBP | USD | CAD ) "CAD">

=== cyrsis/LearnCSharp/_Basic/xml-syntax-fundamentals/8-xml-syntax-fundamentals-m08-validity-exercise-files/invoice.xml
<!DOCTYPE invoice SYSTEM "invoice.dtd">
<invoice>
  <buyer>
    <name>Sam</name>
    <address>Seattle</address>
  </buyer>
  <seller>
    <name>Annie</name>
    <address>Baltimore</address>
  </seller>
  <detail>
    <line>
      <description>Backpack</description>
      <quantity>1</quantity>
      <each>20.00</each>
      <total>20.00</total>
    </line>
  </detail>
  <totals>
    <preTax>20.00</preTax>
    <tax>1.40</tax>
    <tax>1.00</tax>
    <total currency="USD">22.40</total>
  </totals>
</invoice>
